# Generated by Django 5.0.1 on 2024-03-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stash_name", models.CharField(max_length=120)),
                ("thc", models.CharField(max_length=50)),
                ("cbd", models.CharField(max_length=50)),
                ("indica", models.CharField(max_length=50)),
                ("strain_type", models.CharField(max_length=100)),
                ("strain_flavour", models.CharField(max_length=100)),
                ("consumption_method", models.CharField(max_length=100)),
                ("total_quantity", models.CharField(max_length=50)),
                ("stash_image_id", models.CharField(max_length=155)),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
