# Generated by Django 5.0.1 on 2024-03-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stash_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stash",
            name="stash_image_id",
            field=models.CharField(max_length=155),
        ),
    ]
