# Generated by Django 5.0.1 on 2024-03-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cannabis_session", "0001_initial"),
        ("stash_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivitysession",
            name="activity_item",
        ),
        migrations.RemoveField(
            model_name="userconsumptionsession",
            name="stash_id",
        ),
        migrations.AddField(
            model_name="useractivitysession",
            name="activity",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activity_session",
                to="cannabis_session.activity",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userconsumptionsession",
            name="stash",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumption_session",
                to="stash_manager.stash",
            ),
            preserve_default=False,
        ),
    ]
