# Generated by Django 5.0.1 on 2024-02-17 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cannabis_session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsumptionsession",
            name="emotion_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
