# Generated by Django 5.0.1 on 2024-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cannabis_session", "0003_remove_emotion_user_consumption_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="colorHex",
            field=models.CharField(default="FFFFFF", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subemotion",
            name="colorHex",
            field=models.CharField(default="000000", max_length=10),
            preserve_default=False,
        ),
    ]
