# Generated by Django 5.0.1 on 2024-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cannabis_session", "0004_emotion_colorhex_subemotion_colorhex"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsumptionsession",
            name="emotion_subset_id",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
    ]
