# Generated by Django 5.0.1 on 2024-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_biometric_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
